### ISSUE TITLE
New cachable layer

### ISSUE THREAD

**Issue by pvnieo** [veritas9872/PyTorch-Universal-Docker-Template#11]
Hi,

Thank you for the useful template.

Actually, I have some python packages that takes a lot of time to install (c++ binding, takes more than 30 mn), and I want to make them in a separate layer that can be cached, so that it will be installed once after pytorch and before train modules. Can you please direct me to a way to do it?

Thank you in advance.

**Comment by veritas9872** [comment]
I would advise following the style of the PyTorch subsidiary library builds but this depends on what exactly you wish to build/install.

**Comment by veritas9872** [comment]
For a detailed explanation, please read the documentation. I will close this issue but please feel free to reopen if there are any serious issues.
https://docs.docker.com/develop/develop-images/multistage-build
