### ISSUE TITLE
Error importing torch on machines without cuda

### ISSUE THREAD

**Issue by jmspereira** [veritas9872/PyTorch-Universal-Docker-Template#16]
Hello! 

First of all, thank you for the amazing Dockerfile template to build PyTorch from the source!
I was able to use the wheel produced in environments that have CUDA installed, however, in environments that do not have CUDA I am not able of executing the command 'import torch', saying correctly that I do not have CUDA.

This is a large problem for me, the possibility of importing torch in environments that do not have CUDA. Do you know what is the configuration in the build that is causing this? If I use PyTorch from the wheels published by them, I am able of importing torch.

Thank you again!

**Comment by veritas9872** [comment]
Hello. I will close this issue for now but please feel free to reopen it if any other issues occur.
