### ISSUE TITLE
Where is output image located?

### ISSUE THREAD

**Issue by mechatron** [veritas9872/PyTorch-Universal-Docker-Template#19]
Hi sorry for the noob question, but after running the ` make all cc=8.6` command, the build proceeds and complete successfully. My question is where is the output image? There is no .env in the build dir. I'm sorry that I not familiar with Docker build process. Also, I search filesystem(s) but seems like no .env file anywhere. There are some cached ISOs buried deep. I built using WSL2 on Windows 11.

Here is the last bit of output. Cached since I built using custom versions after make all.

>  => CACHED [build-audio 1/3] WORKDIR /opt/audio                                                                    0.0s
>  => CACHED [build-audio 2/3] RUN if [ -n v0.9.1 ]; then     git checkout v0.9.1 &&     git submodule sync &&       0.0s
>  => CACHED [build-audio 3/3] RUN --mount=type=cache,target=/opt/ccache     BUILD_SOX=1 USE_CUDA=1     TORCH_CUDA_  0.0s
>  => CACHED [train-builds 5/5] COPY --from=build-audio /tmp/dist /tmp/dist                                          0.0s
>  => CACHED [train  7/12] COPY --from=train-builds --chown=1000:1000 /opt/conda /opt/conda                          0.0s
>  => CACHED [train  8/12] WORKDIR /home/user/.cache/pip                                                             0.0s
>  => CACHED [train  9/12] WORKDIR /opt/project                                                                      0.0s
>  => CACHED [train 10/12] RUN conda config --set pip_interop_enabled True                                           0.0s
>  => CACHED [train 11/12] RUN conda install -y         numpy==1.20.3 &&     conda clean -ya                         0.0s
>  => CACHED [train 12/12] RUN --mount=type=cache,id=pip-train,target=/home/user/.cache/pip     --mount=type=bind,f  0.0s
>  => exporting to image                                                                                             0.1s
>  => => exporting layers                                                                                            0.0s
>  => => writing image sha256:880af96dacebbb5c70fc602ee499c14e1a45e68154ef7ca6e88c9cd2b437cf27                       0.0s
>  => => naming to docker.io/library/pytorch_source:custom_name

**Comment by veritas9872** [comment]
Use `ls -al` to find `.env`.
Use `docker image ls` to find images.

**Comment by mechatron** [comment]
Thanks for your help.

I found the images but still have issue running: `docker compose up -d --build train` due to CUDA errors.

> failed to solve: rpc error: code = Unknown desc = executor failed running [/bin/sh -c USE_CUDA=${USE_CUDA} USE_CUDNN=${USE_CUDA} USE_ROCM=0     TORCH_NVCC_FLAGS=${TORCH_NVCC_FLAGS}     TORCH_CUDA_ARCH_LIST=${TORCH_CUDA_ARCH_LIST}     CMAKE_PREFIX_PATH="$(dirname $(which conda))/../"     python setup.py bdist_wheel -d /tmp/dist]: exit code: 1

Earlier in the build there were a number of CMake errors relating to CUDA. I'll have to tackle this another time. Thanks again. Closing.

**Comment by veritas9872** [comment]
@mechatron The .env file is meant to be created by the user. It simply stores environment values for docker-compose.yaml. If you have already run make all ..., it should be created automatically, at least in the latest versions.
To create a basic ,env file, please use `make env`.
