### ISSUE TITLE
Build on Ubuntu 18.04 fails [BUG]

### ISSUE THREAD

**Issue by creativeguitar** [veritas9872/PyTorch-Universal-Docker-Template#26]
First of all, thank you so much for working on this!!

**Host information (please complete the following information):**
 - Host OS: Ubuntu 18.04
 - NVIDIA Driver version: 
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Wed_Oct_23_19:32:27_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.2, V10.2.89
```
 - Image CUDA version: 10.2-cudnn8-devel-ubuntu18.04

I am using wsl2 on windows 11. Besides the part that installs the CXX packages took almost 2 whole days (spiked my CPU and Memory and made everything very slow), installation run smoothly almost until the end.

I run into unable to locate package for these 2 packages: python-is-python3, libopenblas0-openmp
and finally I got this message:
`#41 1.398 torch-1.11.0a0+git40eb004-cp38-cp38-linux_x86_64.whl is not a supported wheel on this platform.`

is there a temporary fix that I can implement for these 3 errors to finish the build?

**Comment by creativeguitar** [comment]
I was able to complete the install on ubuntu 18.04 with cuda 10.2

I modify the ARGs to fit my architecture and the last part of the Dockerfile 

```
ARG CUDA_VERSION=10.2
ARG MAGMA_VERSION=102
ARG DISTRO_VERSION=18.04
ARG TORCH_CUDA_ARCH_LIST="5.2 6.0 6.1 7.0 7.5+PTX"
```

```
# Replace the `--mount=...` instructions with `COPY` if BuildKit is unavailable.
# The `readwrite` option is necessary because `apt` needs write permissions on `\tmp`.
ARG PYTHON_VERSION
RUN --mount=type=bind,from=deploy-builds,readwrite,source=/tmp,target=/tmp \
    apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
        software-properties-common build-essential python3.8-dev \
        libtiff5-dev libjpeg8-dev libopenjp2-7-dev zlib1g-dev \
        libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python3-tk \
        libharfbuzz-dev libfribidi-dev libxcb1-dev && \
    add-apt-repository ppa:deadsnakes/ppa && \
    apt-get update && apt-get install -y --no-install-recommends \
        python${PYTHON_VERSION} \
        python3-pip \
#        python-is-python3 \
#        libopenblas0-openmp  \
        libjpeg-turbo8 \
        libpng16-16 && \
    ln -s /usr/bin/python3.8 /usr/bin/python && \
    rm -rf /var/lib/apt/lists/*

# The `mkl` package must be installed for PyTorch to use MKL outside `conda`.
# The `ldconfig` command is necessary for PyTorch to find MKL and other libraries.
RUN --mount=type=bind,from=deploy-builds,readwrite,source=/tmp,target=/tmp \
    python -m pip install Cython && \
    python -m pip install wheel && \
    python -m pip install --upgrade setuptools && \
    echo "tqdm==4.62.3" > /tmp/reqs/pip-deploy.requirements.txt && \
    echo "mkl==2021.2" >> /tmp/reqs/pip-deploy.requirements.txt && \
    python -m pip install --no-cache-dir --find-links /tmp/dist/ \
        -r /tmp/reqs/pip-deploy.requirements.txt \
        /tmp/dist/*.whl && \
    ldconfig

```

**Comment by veritas9872** [comment]
The `python-is-python3` package is only available on Ubuntu 20.04. Please remove it and replace `python` commands with `python3` where necessary.

**Comment by veritas9872** [comment]
The PyTorch build may be slow if your computer does not have enough RAM or too few cores.
Use Task Manager to kill unnecessary processes.
Also, please disable Windows real-time security.

**Comment by veritas9872** [comment]
I will close this issue for now but please feel free to reopen it.
