### ISSUE TITLE
Error in "build-base-ubuntu"

### ISSUE THREAD

**Issue by jhb115** [veritas9872/PyTorch-Universal-Docker-Template#9]
<img width="1026" alt="Screen Shot 2021-10-15 at 4 13 45 PM" src="https://user-images.githubusercontent.com/40454220/137447144-939f18b5-e5fa-49b1-b4c4-75cf4c0b1a60.png">

**Comment by veritas9872** [comment]
Ubuntu 16.04는 이미 EOL이기 때문에 지원되지 않습니다.
